project:
  type: website
  output-dir: _site
  resources:
    - "content/slides/css/**"
    - "content/slides/images/**"
    - "content/slides/r-scripts/**"
  
lang: pt

publish:
  method: gh-pages
  repo: bmebictmar/bme-2026

website:
  page-navigation: true
  title: "BASES DA MATEMÁTICA E ESTATÍSTICA - BME"
  description: "Materiais, cronograma e recursos da UC Bases da Matemática e Estatística do Bict Mar - Unifesp."
  site-url: "https://bmebictmar.github.io/bme-2026"

  repo-url: "https://github.com/bmebictmar/bme-2026"
  open-graph: true

  page-footer:
    right: "BACHARELADO INTERDISCIPLINAR EM CIÊNCIA E TECNOLOGIA DO MAR - Bict Mar - Unifesp"
    left: Bases da Matemática e Estatística - BME
    background: "#296354"

  sidebar: 
    background: "#3b8170"
    logo: "images/logo.png"
    style: "docked"
    search: true
    align: center
    tools:
      - icon: github
        href: https://github.com/bmebictmar/bme-2026
        text: GitHub da UC
      - icon: book
        href: https://moodlegrad.unifesp.br/
        text: Moodle Graduação
      - icon: terminal
        href: https://colab.research.google.com/drive/
        text: Google Colab
    
    collapse-level: 1
    contents:
      - section: "Informações do curso"
        contents:
          - href: course-info/uc-id.qmd
            text: Identificação da UC
          - href: course-info/syllabus.qmd
            text: Plano de Ensino
          - href: index.qmd
            text: Cronograma
          - href: course-info/ebook-tutorial.pdf
            text: Minha biblioteca
            target: "_blank"          
          - href: "https://moodlegrad.unifesp.br/"
            text: Moodle Graduação
            target: "_blank"           
      - section: "Material teórico"
        contents:
          - href: content/slides/slides-bme-geometria-vetores.html
            text: "Aula 2 - A geometria e a álgebra de vetores"
            target: "_blank"
          - href: content/slides/slides-bme-comprimento-angulo.html
            text: "Aula 3 - Comprimento e ângulo: o produto escalar"
            target: "_blank"
          - href: content/slides/slides-bme-sistema-equacoes-lineares.html
            text: "Aulas 4-7 - Sistemas de Equações Lineares"
            target: "_blank"
          - href: https://fcopf.github.io/mead/content/multivariada-numerica/intro-matrizes.html
            text: "Aula 8 - Álgebra de Matrizes"
            target: "_blank"
          - href: content/slides/slides-bme-matriz-leslie.html
            text: "Aula 8 - Matriz de Leslie"
            target: "_blank"
          - href: https://fcopf.github.io/mead/content/regressao-linear/metodo-minimos-quadrados-apresentacao.html
            text: "Aulas 12-14 - Regressão Linear Simples e MMQ"
            target: "_blank"
          - href: https://fcopf.github.io/mead/content/estatistica-descritiva/tendcentral.html
            text: "Aula 15 - Medidas de tendência central"
            target: "_blank"
          - href: https://fcopf.github.io/mead/content/estatistica-descritiva/variacao.html
            text: "Aula 15 - Medidas de variação"
            target: "_blank"
          - href: https://fcopf.github.io/mead/content/medidas-associacao/biquanti.html
            text: "Aula 16 - Associação entre duas variáveis quantitativas"
            target: "_blank"
          - href: https://fcopf.github.io/mead/content/regressao-linear/particao-soma-quadrados-r2.html
            text: "Aula 17 - Partição da soma dos quadrados e coeficiente de determinação"
            target: "_blank"
          - href: content/slides/modelos-matematicos/funcoes-lineares.pdf
            text: "Aula 19 - Funções lineares"
            target: "_blank"
          - href: content/slides/modelos-matematicos/polinomios.pdf
            text: "Aula 20 - Polinômios"
            target: "_blank"
          - href: content/slides/modelos-matematicos/funcoes-potencias.pdf
            text: "Aula 26 - Funções potências"
            target: "_blank"
          - href: content/slides/modelos-matematicos/funcoes-exponenciais-e-logaritmicas.pdf
            text: "Aulas 26-27 - Funções exponenciais e logarítmicas"
            target: "_blank"
          - href: content/slides/modelos-matematicos/funcoes-trigonometricas.pdf
            text: "Aulas 29-32 - Funções trigonométricas"
            target: "_blank"
          - href: content/slides/modelos-matematicos/novas-funcoes-a-partir-de-conhecidas.pdf
            text: "Material complementar - Novas funções a partir de conhecidas"
            target: "_blank"
          
      - section: "Lab. Informática"
        contents:
          - href: https://fcopf.github.io/mead/content/multivariada-numerica/cossine-similarity.html
            text: "Aulas 9 - 10 - Similaridade por cosseno"
            target: "_blank"
          - href: https://fcopf.github.io/mead/content/regressao-linear/mmq-regressao-linear-simples.html
            text: "Aulas 21-22 - MMQ na regressão linear simples"
            target: "_blank"
          - href: https://fcopf.github.io/mead/content/regressao-linear/mmq-regressao-polinomial.html
            text: "Aulas 23-24 - MMQ na regressão polinomial"
            target: "_blank"
          - href: https://fcopf.github.io/mead/content/funcoes-modelos/funcoes-potencia.html
            text: "Aulas 29-30 - Funções de potência"
            target: "_blank"

# Global format configuration
format:
  html:
    theme:
      light: [cosmo, styles/theme.scss]
      dark: [cosmo, styles/theme-dark.scss]
    toc: true
    number-sections: true
    code-copy: true
    code-overflow: wrap

# Configura projeto para ser executado apenas localmente
execute:
  freeze: auto

bibliography: references.bib
